#ifndef _UP_LORA_CONFIG_
#define _UP_LORA_CONFIG_

#define ACTIVE_REGION LORAMAC_REGION_CN470

#ifdef OVER_THE_AIR_ACTIVATION
#undef OVER_THE_AIR_ACTIVATION
#define OVER_THE_AIR_ACTIVATION 0
#endif

#endif // _UP_LORA_CONFIG_